### ISSUE TITLE
RuntimeWarning: coroutine 'Manager.async_shutdown' was never awaited

### ISSUE THREAD

**Issue by umesh-timalsina** [ChimeraPy/Engine#199]
## Reproduce
```python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chimerapy as cp
>>> m = cp.Manager("cp-logs", port=9001)
2023-06-23 15:50:20 [DEBUG] chimerapy-networking: <Server Manager>: running at 192.168.0.66:9001
2023-06-23 15:50:20 [INFO] chimerapy: Manager started at 192.168.0.66:9001
>>> CTRL + D 
Exception ignored in: <function Manager.__del__ at 0x7f29980e63a0>
Traceback (most recent call last):
  File "/home/umesh/isis/oele-isis/ChimeraPy/chimerapy/manager/manager.py", line 439, in __del__
  File "/home/umesh/isis/oele-isis/ChimeraPy/chimerapy/manager/manager.py", line 430, in shutdown
  File "/home/umesh/isis/oele-isis/ChimeraPy/chimerapy/manager/manager.py", line 113, in _exec_coro
  File "/home/umesh/isis/oele-isis/ChimeraPy/chimerapy/networking/async_loop_thread.py", line 56, in exec
TypeError: 'NoneType' object is not callable
sys:1: RuntimeWarning: coroutine 'Manager.async_shutdown' was never awaited
```

**Comment by edavalosanaya** [comment]
Resolved by PR #220, through the use of ``atexit``.
